create table if not exists public.product_categories
(
    is_active          boolean default true,
    category_id        bigint generated by default as identity
        primary key,
    display_order      bigint,
    parent_category_id bigint
        constraint fk6i0mouyrn5rwwd12osu2dgjmf
            references public.product_categories,
    category_name      varchar(50) not null,
    icon_url           varchar(255),
    description        text
);

alter table public.product_categories
    owner to techcycle;

create table if not exists public.product_tags
(
    tag_id      bigint generated by default as identity
        primary key,
    name        varchar(50) not null,
    description text
);

alter table public.product_tags
    owner to techcycle;

create table if not exists public.promotions
(
    active           boolean                     default true,
    discount_value   numeric(10, 2)              not null,
    minimum_purchase numeric(10, 2),
    created_at       timestamp(6) with time zone default CURRENT_TIMESTAMP,
    end_date         timestamp(6) with time zone not null,
    promotion_id     bigint generated by default as identity
        primary key,
    start_date       timestamp(6) with time zone not null,
    code             varchar(50),
    name             varchar(100)                not null,
    promotion_type   varchar(255)                not null
        constraint promotions_promotion_type_check
            check ((promotion_type)::text = ANY
                   ((ARRAY ['DISCOUNT'::character varying, 'TWO_PLUS_ONE'::character varying])::text[])),
    description      text,
    rules            jsonb
);

alter table public.promotions
    owner to techcycle;

create table if not exists public.roles
(
    role_id     bigint generated by default as identity
        primary key,
    role_name   varchar(20) not null,
    description text
);

alter table public.roles
    owner to techcycle;

create table if not exists public.users
(
    email_verified        boolean     default false,
    two_factor_enabled    boolean     default false,
    created_at            timestamp(6) with time zone,
    failed_login_attempts bigint      default 0,
    last_login            timestamp(6) with time zone,
    updated_at            timestamp(6) with time zone,
    user_id               bigint generated by default as identity
        primary key,
    account_status        varchar(20) default 'ACTIVE'::character varying,
    phone_number          varchar(20),
    first_name            varchar(50),
    last_name             varchar(50),
    username              varchar(50)  not null,
    email                 varchar(100) not null,
    avatar_url            varchar(255),
    password              varchar(255) not null,
    preferences           jsonb
);

alter table public.users
    owner to techcycle;

create table if not exists public.addresses
(
    address_id     bigint generated by default as identity
        primary key,
    user_id        bigint
        constraint fk1fa36y2oqhao3wgg2rw1pi459
            references public.users,
    postal_code    varchar(20),
    city           varchar(100) not null,
    country        varchar(100) not null,
    state          varchar(100),
    street_address text         not null
);

alter table public.addresses
    owner to techcycle;

create table if not exists public.notifications
(
    is_read           boolean                     default false,
    created_at        timestamp(6) with time zone default CURRENT_TIMESTAMP,
    notification_id   bigint generated by default as identity
        primary key,
    read_at           timestamp(6) with time zone,
    user_id           bigint
        constraint fk9y21adhxn0ayjhfocscqox7bh
            references public.users,
    title             varchar(200),
    notification_type varchar(255) not null
        constraint notifications_notification_type_check
            check ((notification_type)::text = ANY
                   ((ARRAY ['MESSAGE'::character varying, 'DELIVERY'::character varying, 'ORDER'::character varying])::text[])),
    content           text,
    data              jsonb
);

alter table public.notifications
    owner to techcycle;

create table if not exists public.orders
(
    discount_amount     numeric(10, 2)              default 0,
    shipping_cost       numeric(10, 2) not null,
    subtotal            numeric(10, 2) not null,
    tax_amount          numeric(10, 2) not null,
    total_amount        numeric(10, 2) not null,
    created_at          timestamp(6) with time zone default CURRENT_TIMESTAMP,
    order_id            bigint generated by default as identity
        primary key,
    shipping_address_id bigint
        constraint fkmk6q95x8ffidq82wlqjaq7sqc
            references public.addresses,
    updated_at          timestamp(6) with time zone default CURRENT_TIMESTAMP,
    user_id             bigint
        constraint fk32ql8ubntj5uh44ph9659tiih
            references public.users,
    status              varchar(20)    not null
        constraint orders_status_check
            check ((status)::text = ANY
                   ((ARRAY ['PENDING'::character varying, 'PROCESSING'::character varying, 'DELIVERED'::character varying, 'SHIPPED'::character varying, 'CANCELLED'::character varying])::text[])),
    ip_address          varchar(45),
    payment_method      varchar(255)   not null
        constraint orders_payment_method_check
            check ((payment_method)::text = ANY
                   ((ARRAY ['CARD'::character varying, 'AT_DOOR'::character varying])::text[])),
    notes               text,
    user_agent          text
);

alter table public.orders
    owner to techcycle;

create table if not exists public.conversation_threads
(
    assigned_to      bigint
        constraint fkt6t9ngdogvxo57ib2qdkb9ym1
            references public.users,
    created_at       timestamp(6) with time zone default CURRENT_TIMESTAMP,
    created_by       bigint
        constraint fkhn5y0isn6ov4pf2x03xpyu7sm
            references public.users,
    related_order_id bigint
        constraint fkj4n3piyt5hflo7v1t1acoa38k
            references public.orders,
    thread_id        bigint generated by default as identity
        primary key,
    updated_at       timestamp(6) with time zone default CURRENT_TIMESTAMP,
    status           varchar(20)
        constraint conversation_threads_status_check
            check ((status)::text = ANY ((ARRAY ['OPEN'::character varying, 'CLOSED'::character varying])::text[])),
    subject          varchar(200)
);

alter table public.conversation_threads
    owner to techcycle;

create table if not exists public.messages
(
    created_at   timestamp(6) with time zone default CURRENT_TIMESTAMP,
    message_id   bigint generated by default as identity
        primary key,
    receiver_id  bigint
        constraint fkt05r0b6n0iis8u7dfna4xdh73
            references public.users,
    sender_id    bigint
        constraint fk4ui4nnwntodh6wjvck53dbk9m
            references public.users,
    thread_id    bigint
        constraint fkjv6x5vxrpvjrmkkhplerlpm7y
            references public.conversation_threads,
    message_text text not null
);

alter table public.messages
    owner to techcycle;

create table if not exists public.order_status_history
(
    created_at timestamp(6) with time zone default CURRENT_TIMESTAMP,
    created_by bigint
        constraint fkkd0ovq7qhfq1ni7huqpho7god
            references public.users,
    history_id bigint generated by default as identity
        primary key,
    order_id   bigint
        constraint fknmcbg3mmbt8wfva97ra40nmp3
            references public.orders,
    status     varchar(20) not null,
    comment    text
);

alter table public.order_status_history
    owner to techcycle;

create table if not exists public.search_logs
(
    created_at    timestamp(6) with time zone default CURRENT_TIMESTAMP,
    results_count bigint,
    search_id     bigint generated by default as identity
        primary key,
    user_id       bigint
        constraint fkaxl330wos94o6v1a13oyvgqr0
            references public.users,
    session_id    varchar(100),
    filters       jsonb,
    results       jsonb,
    search_query  text
);

alter table public.search_logs
    owner to techcycle;

create table if not exists public.shopping_carts
(
    cart_id    bigint generated by default as identity
        primary key,
    created_at timestamp(6) with time zone default CURRENT_TIMESTAMP,
    updated_at timestamp(6) with time zone default CURRENT_TIMESTAMP,
    user_id    bigint
        constraint fk3iw2988ea60alsp0gnvvyt744
            references public.users,
    status     varchar(20)
        constraint shopping_carts_status_check
            check ((status)::text = ANY
                   ((ARRAY ['ACTIVE'::character varying, 'ARCHIVED'::character varying, 'ORDERED'::character varying, 'CANCELLED'::character varying])::text[])),
    session_id varchar(100)
);

alter table public.shopping_carts
    owner to techcycle;

create table if not exists public.user_roles
(
    assigned_at   timestamp(6) with time zone default CURRENT_TIMESTAMP,
    role_id       bigint
        constraint fkh8ciramu9cc9q3qcqiv4ue8a6
            references public.roles,
    user_id       bigint
        constraint fkhfh9dx7w3ubf1co1vdev94g3f
            references public.users,
    user_roles_id bigint generated by default as identity
        primary key
);

alter table public.user_roles
    owner to techcycle;

create table if not exists public.brands
(
    brand_id    bigint generated by default as identity
        primary key,
    description varchar(255),
    name        varchar(255) not null
);

alter table public.brands
    owner to techcycle;

create table if not exists public.products
(
    is_featured          boolean default false,
    manufacturing_date   date,
    price                numeric(10, 2) not null,
    weight               numeric(10, 2),
    brand_id             bigint
        constraint fka3a4mpsfdf4d2y6r8ra3sc8mv
            references public.brands,
    low_stock_threshold  bigint  default 5,
    product_id           bigint generated by default as identity
        primary key,
    stock_quantity       bigint         not null,
    condition            varchar(20)    not null,
    status               varchar(20)
        constraint products_status_check
            check ((status)::text = ANY ((ARRAY ['ACTIVE'::character varying, 'ARCHIVED'::character varying])::text[])),
    model_number         varchar(50),
    name                 varchar(100)   not null,
    description          text,
    detailed_description text,
    dimensions           jsonb,
    technical_specs      jsonb,
    warranty_info        text
);

alter table public.products
    owner to techcycle;

create table if not exists public.cart_items
(
    saved_for_later boolean                     default false,
    added_at        timestamp(6) with time zone default CURRENT_TIMESTAMP,
    cart_id         bigint
        constraint fkojy3ibx281qswho045bw4q0da
            references public.shopping_carts,
    cart_items_id   bigint generated by default as identity
        primary key,
    product_id      bigint
        constraint fk1re40cjegsfvw58xrkdp6bac6
            references public.products,
    quantity        bigint not null
);

alter table public.cart_items
    owner to techcycle;

create table if not exists public.order_items
(
    discount_amount numeric(10, 2) default 0,
    price_at_time   numeric(10, 2) not null,
    tax_amount      numeric(10, 2) default 0,
    total_amount    numeric(10, 2) not null,
    order_id        bigint
        constraint fkbioxgbv59vetrxe0ejfubep1w
            references public.orders,
    order_items_id  bigint generated by default as identity
        primary key,
    product_id      bigint
        constraint fkocimc7dtr037rh4ls4l95nlfi
            references public.products,
    quantity        bigint         not null
);

alter table public.order_items
    owner to techcycle;

create table if not exists public.product_categories_mapping
(
    is_primary                    boolean                     default false,
    category_id                   bigint
        constraint fkf59p8l3wctrgd7djo0foto37i
            references public.product_categories,
    created_at                    timestamp(6) with time zone default CURRENT_TIMESTAMP,
    product_categories_mapping_id bigint generated by default as identity
        primary key,
    product_id                    bigint
        constraint fkgt211hr27wnwo0v8wbdubqbki
            references public.products
);

alter table public.product_categories_mapping
    owner to techcycle;

create table if not exists public.product_images
(
    is_primary    boolean default false,
    display_order bigint,
    image_id      bigint generated by default as identity
        primary key,
    product_id    bigint
        constraint fkqnq71xsohugpqwf3c9gxmsuy
            references public.products,
    alt_text      varchar(100),
    title         varchar(100),
    image_url     text not null,
    bytes         bytea
);

alter table public.product_images
    owner to techcycle;

create table if not exists public.product_reviews
(
    created_at timestamp(6) with time zone default CURRENT_TIMESTAMP,
    product_id bigint
        constraint fk35kxxqe2g9r4mww80w9e3tnw9
            references public.products,
    rating     bigint,
    review_id  bigint generated by default as identity
        primary key,
    user_id    bigint
        constraint fk58i39bhws2hss3tbcvdmrm60f
            references public.users,
    title      varchar(100),
    comment    text
);

alter table public.product_reviews
    owner to techcycle;

create table if not exists public.product_tags_mapping
(
    product_id              bigint
        constraint fk31ur1te5soskfpeb6xhyestlw
            references public.products,
    product_tags_mapping_id bigint generated by default as identity
        primary key,
    tag_id                  bigint
        constraint fkdkivwthfqwgpth14tkajdexw9
            references public.product_tags
);

alter table public.product_tags_mapping
    owner to techcycle;

create table if not exists public.user_product_interactions
(
    created_at       timestamp(6) with time zone default CURRENT_TIMESTAMP,
    duration         bigint,
    interaction_id   bigint generated by default as identity
        primary key,
    product_id       bigint
        constraint fkoeyihaue2tbnt8cl65x01h5h3
            references public.products,
    user_id          bigint
        constraint fkrgrm7uupx9c9r1a2duy9mrkq8
            references public.users,
    interaction_type varchar(20)
        constraint user_product_interactions_interaction_type_check
            check ((interaction_type)::text = ANY
                   ((ARRAY ['HOVER'::character varying, 'CLICKED'::character varying, 'ORDERED'::character varying, 'PUT_IN_CART'::character varying, 'REVIEWED'::character varying])::text[])),
    source           varchar(50)
);

alter table public.user_product_interactions
    owner to techcycle;

